import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { AGENT_ROLES } from '../engine/role-manager.js';

export interface McpConfig {
  name: string;
  config: {
    type: 'local' | 'remote';
    command?: string[];
    url?: string;
    headers?: Record<string, string>;
    environment?: Record<string, string>;
  };
}

/** MCP servers that must be present in opencode config. Add new entries here. */
export const REQUIRED_MCPS: McpConfig[] = [
  {
    name: 'playwright',
    config: {
      type: 'local',
      command: ['npx', '-y', '@playwright/mcp'],
    },
  },
];

/**
 * Check opencode global config for required MCP servers.
 * Missing ones are written directly into the config file.
 * Returns { installed: names added, alreadyExists: names already present }.
 */
export function ensureRequiredMcps(): { installed: string[]; alreadyExists: string[] } {
  const configPath = path.join(os.homedir(), '.config', 'opencode', 'opencode.json');

  let config: Record<string, unknown> = {};
  if (fs.existsSync(configPath)) {
    try {
      config = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
    } catch {
      /* corrupted config — will be overwritten */
    }
  } else {
    // Ensure directory exists
    fs.mkdirSync(path.dirname(configPath), { recursive: true });
  }

  const mcp = (config.mcp ?? {}) as Record<string, unknown>;
  const installed: string[] = [];
  const alreadyExists: string[] = [];

  for (const required of REQUIRED_MCPS) {
    if (mcp[required.name]) {
      alreadyExists.push(required.name);
    } else {
      mcp[required.name] = required.config;
      installed.push(required.name);
    }
  }

  if (installed.length > 0) {
    config.mcp = mcp;
    fs.writeFileSync(configPath, JSON.stringify(config, null, 4), 'utf-8');
  }

  return { installed, alreadyExists };
}

/**
 * Validate role prompts exist in .win-agent/roles/.
 * Returns list of roles that have valid prompt files.
 */
export function syncAgents(workspace: string): string[] {
  const rolesDir = path.join(workspace, '.win-agent', 'roles');
  const validated: string[] = [];

  for (const role of AGENT_ROLES) {
    const promptFile = path.join(rolesDir, `${role}.md`);
    if (fs.existsSync(promptFile)) {
      validated.push(role);
    } else {
      console.log(`   ⚠️  角色文件不存在: ${role}.md`);
    }
  }

  return validated;
}

/**
 * Deploy custom tools to .opencode/tools/.
 * Copies the database tool template to the workspace.
 */
export function deployTools(workspace: string): void {
  const toolsDir = path.join(workspace, '.opencode', 'tools');
  fs.mkdirSync(toolsDir, { recursive: true });

  // Remove legacy shared tool file
  const legacyFile = path.join(toolsDir, 'database.ts');
  if (fs.existsSync(legacyFile)) fs.unlinkSync(legacyFile);

  // Generate per-role database tools with hardcoded role name
  for (const role of AGENT_ROLES) {
    const toolContent = renderDatabaseToolSource(role);
    const toolFile = path.join(toolsDir, `database_${role}.ts`);
    fs.writeFileSync(toolFile, toolContent, 'utf-8');
  }
}

const DATABASE_TOOL_TEMPLATE_FILE = 'database-tool.template.ts';

function getDatabaseToolTemplatePath(): string {
  const here = path.dirname(fileURLToPath(import.meta.url));
  const inBundledWorkspace = path.join(here, 'workspace', DATABASE_TOOL_TEMPLATE_FILE);
  const alongsideModule = path.join(here, DATABASE_TOOL_TEMPLATE_FILE);
  if (fs.existsSync(inBundledWorkspace)) return inBundledWorkspace;
  if (fs.existsSync(alongsideModule)) return alongsideModule;
  throw new Error(
    `Missing database tool template: tried ${inBundledWorkspace} and ${alongsideModule}`
  );
}

/**
 * Render the database tool source for a role (for deploy or tests).
 * Replaces `__WIN_AGENT_ROLE__` and `__WIN_AGENT_DB_REL_PATH__` in `database-tool.template.ts`.
 */
export function renderDatabaseToolSource(role: string): string {
  const dbRelPath = '.win-agent/win-agent.db';
  let source = fs.readFileSync(getDatabaseToolTemplatePath(), 'utf-8');
  source = source.replaceAll('__WIN_AGENT_ROLE__', role);
  source = source.replaceAll('__WIN_AGENT_DB_REL_PATH__', dbRelPath);
  return `// Auto-generated by win-agent — do not edit manually (role: ${role})\n${source}`;
}
